#!/bin/bash

# Copyright (C) 2018 David De Grave <david@ledav.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Included from all projects/*/post-build-hook scripts.

logSubTitle "Executing common tasks ..."

if [ -e "$TARGET_DIR"/root/.ssh/authorized_keys ]
then
	log "Populating '{TARGET}/root/.ssh/autorized_keys' with defined ssh keys ..."
	[ -z "$SSH_KEYS" ] && \
		die "Please set SSH_KEYS array with the authorized ssh keys (check 'secure' file) !"

	for k in "${SSH_KEYS[@]}"; do
		echo "$k" >> "$TARGET_DIR"/root/.ssh/authorized_keys
	done
fi

logSubTitle "Common tasks done!"
