#!/bin/bash

# Copyright (C) 2018 David De Grave <david@ledav.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

MAINDIR=$(sed -n 's/BR2_DEFCONFIG="\(.*_defconfig\)"/\1/ p' < "$BR2_CONFIG")
MAINDIR=$(readlink -f "${MAINDIR%/*}/..")
SCRNAME=$(readlink -f "$0")
SCRNAME=${SCRNAME#$MAINDIR/}

. "$MAINDIR"/scripts/include/log || exit 1

logTitle "Running $SCRNAME ..."

# CODE HERE

logTitle "$SCRNAME done!"
exit 0
