#!/bin/bash

# Copyright (C) 2018 David De Grave <david@ledav.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

MAINDIR=$(sed -n 's/BR2_DEFCONFIG="\(.*_defconfig\)"/\1/ p' < "$BR2_CONFIG")
MAINDIR=$(readlink -f "${MAINDIR%/*}/..")
SCRNAME=$(readlink -f "$0")
SCRNAME=${SCRNAME#$MAINDIR/}

. "$MAINDIR"/scripts/include/log || exit 1

logTitle "Running $SCRNAME ..."

BOARD_DIR="$(dirname $0)"

# copy the uEnv.txt to the output/images directory
rm -f "$BINARIES_DIR"/uEnv.txt
cp -f "$MAINDIR"/board/beaglebone/uEnv.txt "$BINARIES_DIR"/uEnv.txt

[ -e "$BINARIES_DIR"/zImage.dht11 ] && mv -vf "$BINARIES_DIR"/{zImage.dht11,zImage}

GENIMAGE_CFG="${BOARD_DIR}/genimage.cfg"
GENIMAGE_TMP="${BUILD_DIR}/genimage.tmp"

rm -rf "${GENIMAGE_TMP}"

genimage \
	--rootpath   "${TARGET_DIR}" \
	--inputpath  "${BINARIES_DIR}" \
	--outputpath "${BINARIES_DIR}" \
	--tmppath    "${GENIMAGE_TMP}" \
	--config     "${GENIMAGE_CFG}"

rm -rf "$O"/final
mkdir "$O"/final
cp -ar	"$MAINDIR"/scripts/{flash.sh,include} \
	"$O"/final

mv "$BINARIES_DIR"/sdcard.img \
	"$O"/final

logTitle "$SCRNAME done!"
exit 0
