#!/bin/sh
#
# Starts cron daemon
#

umask 077

start() {
	printf "Starting crond: "
	start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/crond.pid --background --exec /usr/sbin/crond -- -f
	echo "OK"
}
stop() {
	printf "Stopping crond: "
	start-stop-daemon --stop --quiet --pidfile /var/run/crond.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

